/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blur_money_account */

#ifndef _Included_com_blur_money_account
#define _Included_com_blur_money_account
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blur_money_account
 * Method:    new_account
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_blur_money_account_new_1account
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_blur_money_account
 * Method:    get_transactions
 * Signature: ()[Lcom/blur/money/transaction;
 */
JNIEXPORT jobjectArray JNICALL Java_com_blur_money_account_get_1transactions
  (JNIEnv *, jobject);

/*
 * Class:     com_blur_money_account
 * Method:    get_name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_blur_money_account_get_1name
  (JNIEnv *, jobject);

/*
 * Class:     com_blur_money_account
 * Method:    get_id
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_blur_money_account_get_1id
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
