/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blur_money_transaction */

#ifndef _Included_com_blur_money_transaction
#define _Included_com_blur_money_transaction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blur_money_transaction
 * Method:    get_name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_blur_money_transaction_get_1name
  (JNIEnv *, jobject);

/*
 * Class:     com_blur_money_transaction
 * Method:    get_id
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_blur_money_transaction_get_1id
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
