/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blur_money_maingui */

#ifndef _Included_com_blur_money_maingui
#define _Included_com_blur_money_maingui
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blur_money_maingui
 * Method:    jni_main
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_blur_money_maingui_jni_1main
  (JNIEnv *, jobject);

/*
 * Class:     com_blur_money_maingui
 * Method:    jni_notify_input
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_blur_money_maingui_jni_1notify_1input
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
