/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blur_money_file_bank */

#ifndef _Included_com_blur_money_file_bank
#define _Included_com_blur_money_file_bank
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blur_money_file_bank
 * Method:    new_file_bank
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_blur_money_file_1bank_new_1file_1bank
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_blur_money_file_bank
 * Method:    del
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_blur_money_file_1bank_del
  (JNIEnv *, jobject);

/*
 * Class:     com_blur_money_file_bank
 * Method:    load
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_blur_money_file_1bank_load
  (JNIEnv *, jobject);

/*
 * Class:     com_blur_money_file_bank
 * Method:    save
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_blur_money_file_1bank_save
  (JNIEnv *, jobject);

/*
 * Class:     com_blur_money_file_bank
 * Method:    get_accounts
 * Signature: ()[Lcom/blur/money/account;
 */
JNIEXPORT jobjectArray JNICALL Java_com_blur_money_file_1bank_get_1accounts
  (JNIEnv *, jobject);

/*
 * Class:     com_blur_money_file_bank
 * Method:    add_account
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_blur_money_file_1bank_add_1account
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_blur_money_file_bank
 * Method:    get_account
 * Signature: (I)Lcom/blur/money/account;
 */
JNIEXPORT jobject JNICALL Java_com_blur_money_file_1bank_get_1account
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_blur_money_file_bank
 * Method:    delete_account
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_blur_money_file_1bank_delete_1account
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
