/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blur_money_file_bank */

#ifndef _Included_com_blur_money_file_bank
#define _Included_com_blur_money_file_bank
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blur_money_file_bank
 * Method:    new_file_bank
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_blur_money_file_1bank_new_1file_1bank
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_blur_money_file_bank
 * Method:    load
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_blur_money_file_1bank_load
  (JNIEnv *, jobject);

/*
 * Class:     com_blur_money_file_bank
 * Method:    get_accounts
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_blur_money_file_1bank_get_1accounts
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
