/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blur_money_transaction */

#ifndef _Included_com_blur_money_transaction
#define _Included_com_blur_money_transaction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blur_money_transaction
 * Method:    new_transaction
 * Signature: (Ljava/lang/String;FJ)V
 */
JNIEXPORT void JNICALL Java_com_blur_money_transaction_new_1transaction__Ljava_lang_String_2FJ
  (JNIEnv *, jobject, jstring, jfloat, jlong);

/*
 * Class:     com_blur_money_transaction
 * Method:    new_transaction
 * Signature: (Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_com_blur_money_transaction_new_1transaction__Ljava_lang_String_2F
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     com_blur_money_transaction
 * Method:    new_transaction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_blur_money_transaction_new_1transaction__
  (JNIEnv *, jobject);

/*
 * Class:     com_blur_money_transaction
 * Method:    del
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_blur_money_transaction_del
  (JNIEnv *, jobject);

/*
 * Class:     com_blur_money_transaction
 * Method:    get_name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_blur_money_transaction_get_1name
  (JNIEnv *, jobject);

/*
 * Class:     com_blur_money_transaction
 * Method:    get_id
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_blur_money_transaction_get_1id
  (JNIEnv *, jobject);

/*
 * Class:     com_blur_money_transaction
 * Method:    get_amount
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_blur_money_transaction_get_1amount
  (JNIEnv *, jobject);

/*
 * Class:     com_blur_money_transaction
 * Method:    get_when
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_blur_money_transaction_get_1when
  (JNIEnv *, jobject);

/*
 * Class:     com_blur_money_transaction
 * Method:    get_comment
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_blur_money_transaction_get_1comment
  (JNIEnv *, jobject);

/*
 * Class:     com_blur_money_transaction
 * Method:    set_name
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_blur_money_transaction_set_1name
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_blur_money_transaction
 * Method:    set_amount
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_blur_money_transaction_set_1amount
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_blur_money_transaction
 * Method:    set_when
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_blur_money_transaction_set_1when
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
